### ISSUE TITLE
Consider enforcing use of JSDoc comments

### ISSUE THREAD

**Issue by pdewouters** [humanmade/coding-standards#157]
ESlint provides rulesets for enforcing and checking JSDoc comments.
`valid-jsdoc` and `require-jsdoc`

https://eslint.org/docs/rules/valid-jsdoc
https://eslint.org/docs/rules/require-jsdoc

**Comment by mikeselander** [comment]
I am strongly in support of adding these rules 👍 it will cause a decent amount of errors on some projects, but I think that's a worthy cost for encouraging valid documentation in JS.

@humanmade/frontend anyone have further thoughts on this?

**Comment by pdewouters** [comment]
ah nice one - it wasn't obvious on that doc page

**Comment by rmccue** [comment]
Provided we set `require-jsdoc` to `publicOnly` rather than all functions, 👍

**Comment by mikeselander** [comment]
Why do you only want docblocks on exported functions? 

We tend to have a pattern whereby we put heavy logic into internal functions and only export a wrapper function that handles some DOM hooks or integration details for a module. Limiting this rule to only exported, or "public", functions would really reduce the efficacy of this change.

**Comment by rmccue** [comment]
JavaScript tends to involve a lot more functions and their usage thereof, so requiring documentation on all functions would increase the burden to write code substantially. Particularly for arrow functions as callbacks, which are otherwise uninteresting.

I think I'd be OK with the scenario you describe, as the wrapper function is the public interface, which is really where documentation is needed most. Documenting the reasons behind internal implementation decisions is also useful, but at a different level.

**Comment by mattheu** [comment]
Question about React components - which is maybe worth clarifying expectations here.

Something I've run into is duplication between `jsdoc` and `PropTypes`.

JSDoc allows you to document properties of object params, so you can use it to document all props. However as this is already covered by PropTypes so feels redundant to me.

Which means we're left with pretty arbitrary documentation for the props `param`.

Here's an example: 

```jsx
/**
 * Author component
 *
 * @param {Object} props
 * @param {number} props.id
 * @param {string} props.name
 * @param {string} props.link
 *
 * @returns {*}
 */
const PostAuthor = ( {
	id,
	name,
	link,
} ) => {
	return (
		...
	)
};

PostAuthor.propTypes = {
	id: PropTypes.number.isRequired,
	name: PropTypes.string.isRequired,
	link PropTypes.string.isRequired,
};
```

**Comment by shadyvb** [comment]
While the example does show the redundancy, one could argue the importance of prop descriptions that are not really possible with proptypes AFAIK.

**Comment by rmccue** [comment]
The proptypes pattern for adding descriptions is:

```
PostAuthor.propTypes = {
	/** ID for the author **/
	id: PropTypes.number.isRequired,

	/** Name to display **/
	name: PropTypes.string.isRequired,
};
```

This is supported by the official PropTypes parser which is used to generate documentation, and which Storybook uses to render prop tables.

**Comment by mikeselander** [comment]
>JavaScript tends to involve a lot more functions and their usage thereof, so requiring documentation on all functions would increase the burden to write code substantially. Particularly for arrow functions as callbacks, which are otherwise uninteresting.

I'd be OK with disabling this for arrow functions used as callbacks. I think that this rule has more value for first-class functions with important logic in them. I would argue that writing docblocks is not a huge burden. It's much less of a burden than coming back in a year and having to interpret what yourself or another developer wrote.

> I think I'd be OK with the scenario you describe, as the wrapper function is the public interface, which is really where documentation is needed most. Documenting the reasons behind internal implementation decisions is also useful, but at a different level.

Perhaps a more thorough example would be useful here. 

This is from a real module on a recent client:

These are examples of functions that are involved in said module:

```js
const fetchMorePosts = filters => {...}
const incrementPage = page => {...}
const outputPostsOnPage = ( output, append = true ) => {...}
const removeLoadMore =() => {...}
```

Each of the above modules has important and complex logic that needs to be explained further. For example, on `incrementPage` is `page` an object, is it an integer, is it a string? Does it return a page number or pass this to another function? You might not be able to answer all of these questions by reading the code itself since JS is so loose. These are the kinds of ambiguity that docblocks (and/or TS) should remove.

In contrast, this is the public access to the module:
```js
const init = () => {
	if ( ! getLoadMoreBtn() ) {
		return;
	}

	getLoadMoreBtn().addEventListener( 'click', handleClick );
};
```

This effectively does nothing, and any documentation for this function is worthless but would be the only place where documentation would be required via `publicOnly`.

**Comment by joehoyle** [comment]
Perhaps we should look at whether requireing PHP Doc comments is something we'd want to do first?

**Comment by mikeselander** [comment]
@joehoyle That was recently added in #177, but I don't see how that would help inform this discussion?

**Comment by joehoyle** [comment]
@mikeselander my point was that I think this decision has a lerger impact on PHP, so we should make that decision first. As it happens I didn't realize #177 had been done, so that point is now moot. As you mentioned on the issue, that change is going to be huge though!

**Comment by mikeselander** [comment]
> As you mentioned on the issue, that change is going to be huge though!

Most definitely - I figured this was best in the next release as it's a major version and will likely include some breaking changes already.

**Comment by kadamwhite** [comment]
:+1: for requiring JSDoc on functions. :+1: on _not_ enforcing it for nested functions like arrow callbacks.

Also, if we're using TypeScript then JSDoc param annotations become unnecessarily duplicative; but I'd still want a function comment in the code, even if we omit params/returns in favor of TS.
