### ISSUE TITLE
Update eslint-config-humanmade peer dependencies

### ISSUE THREAD

**Issue by rmccue** [humanmade/coding-standards#56]
The peer dependencies of our ESLint config need to be updated for ESLint 4:

```
warning " > eslint-config-react-app@0.5.2" has incorrect peer dependency "eslint@^3.8.1".
warning " > eslint-plugin-jsx-a11y@2.2.3" has incorrect peer dependency "eslint@^2.10.2 || 3.x".                                                                                    
warning " > eslint-plugin-react@6.10.3" has incorrect peer dependency "eslint@^2.0.0 || ^3.0.0".  
```

**Comment by pdewouters** [comment]
```
warning " > eslint-config-humanmade@0.4.2" has incorrect peer dependency "babel-eslint@^7.0.0".
warning " > eslint-config-humanmade@0.4.2" has unmet peer dependency "eslint-config-react-app@^0.5.0".
warning " > eslint-config-humanmade@0.4.2" has incorrect peer dependency "eslint-plugin-jsx-a11y@^2.2.3".
warning " > eslint-config-humanmade@0.4.2" has incorrect peer dependency "eslint-plugin-react@^6.4.1".
```

**Comment by kadamwhite** [comment]
@rmccue I'm working on this, but it's a branch off of #42 because then we can actually test that the upgrades work without linking into another project, so if we can land #42 that'd be a big help!

**Comment by kucrut** [comment]
Upon upgrading to version `0.5.0`, I got

```
warning " > eslint-config-react-app@2.1.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@^5.1.1".
```

**Comment by kadamwhite** [comment]
`eslint-config-react-app` has used v6.0.2 of `eslint-plugin-jsx-a11y` since January, but there hasn't been a release since. :crossed_fingers: that we'll get one soon (which would automatically resolve that part of this issue, although it will also force us to upgrade to babel-eslint ^8.2!)

In the meantime, other than producing noise on installation the warning should be safe to ignore.
